#ifndef __UI_H__
#define __UI_H__

#include <stdint.h>

void ui(void);
void ui_init(void);
void ui_10ms_tick(void);
void ui_1s_tick(void);
void phone_flash_to_ascii(uint8_t *dataout, uint8_t flash_id);
void var_to_ascii(uint8_t var, uint8_t aux_buffer[]);

#define MSG_DISP_TIME_SHORT	3
#define MSG_DISP_TIME_LONG	12
#define PASS_SIZE			8
#define CELL_SIZE			12
#define TAG_SIZE			10
#define T_LOW_POWER		180

// Display vars
enum{DISP_P0, DISP_P1, DISP_BATT};
enum{SMALL, LARGE};

// LCD 'y' rows
enum{L0, L1, L2, L3, L4, L5};

// Menus
enum{MS_ALARM, MS_SYS, MS_CELL, MS_COM, MS_SENSOR};

// States 
enum{
UI_MAIN_BUTTON_A, UI_MAIN_BUTTON_B,

UI_LOGIN_BUTTON_A, UI_LOGIN_BUTTON_B,

UI_ENTER_SCREEN, UI_ENTER_BUTTON_A, UI_ENTER_BUTTON_B,

ALARM_IN_H_0, ALARM_IN_H_1, ALARM_IN_H_BUTTON_A, ALARM_IN_H_BUTTON_B,
ALARM_IN_H_HIST_0, ALARM_IN_H_HIST_1, ALARM_IN_H_HIST_BUTTON_A, ALARM_IN_H_HIST_BUTTON_B,
ALARM_IN_H_MODE_0, ALARM_IN_H_MODE_1, ALARM_IN_H_MODE_BUTTON_A, ALARM_IN_H_MODE_BUTTON_B,
ALARM_IN_L_0, ALARM_IN_L_1, ALARM_IN_L_BUTTON_A, ALARM_IN_L_BUTTON_B,
ALARM_IN_L_HIST_0, ALARM_IN_L_HIST_1, ALARM_IN_L_HIST_BUTTON_A, ALARM_IN_L_HIST_BUTTON_B,
ALARM_IN_L_MODE_0, ALARM_IN_L_MODE_1, ALARM_IN_L_MODE_BUTTON_A, ALARM_IN_L_MODE_BUTTON_B,

ALARM_OUT_H_0, ALARM_OUT_H_1, ALARM_OUT_H_BUTTON_A, ALARM_OUT_H_BUTTON_B,
ALARM_OUT_H_HIST_0, ALARM_OUT_H_HIST_1, ALARM_OUT_H_HIST_BUTTON_A, ALARM_OUT_H_HIST_BUTTON_B,
ALARM_OUT_H_MODE_0, ALARM_OUT_H_MODE_1, ALARM_OUT_H_MODE_BUTTON_A, ALARM_OUT_H_MODE_BUTTON_B,
ALARM_OUT_L_0, ALARM_OUT_L_1, ALARM_OUT_L_BUTTON_A, ALARM_OUT_L_BUTTON_B,
ALARM_OUT_L_HIST_0, ALARM_OUT_L_HIST_1, ALARM_OUT_L_HIST_BUTTON_A, ALARM_OUT_L_HIST_BUTTON_B,
ALARM_OUT_L_MODE_0, ALARM_OUT_L_MODE_1, ALARM_OUT_L_MODE_BUTTON_A, ALARM_OUT_L_MODE_BUTTON_B,

ALARM_MASK_0, ALARM_MASK_1, ALARM_MASK_BUTTON_A, ALARM_MASK_BUTTON_B,

ALARM_END,

SYS_CLOCK_0, SYS_CLOCK_1, SYS_CLOCK_BUTTON_A, SYS_CLOCK_BUTTON_B,
SYS_TAG_0, SYS_TAG_1, SYS_TAG_BUTTON_A, SYS_TAG_BUTTON_B,
SYS_PASS_0, SYS_PASS_1, SYS_PASS_BUTTON_A, SYS_PASS_BUTTON_B,
SYS_END,

CELL_REP_0, CELL_REP_1, CELL_REP_BUTTON_A, CELL_REP_BUTTON_B,
CELL_RETRIES_0, CELL_RETRIES_1, CELL_RETRIES_BUTTON_A, CELL_RETRIES_BUTTON_B,
CELL_RETRIES_T_0, CELL_RETRIES_T_1, CELL_RETRIES_T_BUTTON_A, CELL_RETRIES_T_BUTTON_B,
CELL_0_0, CELL_0_1, CELL_0_BUTTON_A, CELL_0_BUTTON_B,
CELL_1_0, CELL_1_1, CELL_1_BUTTON_A, CELL_1_BUTTON_B,
CELL_2_0, CELL_2_1, CELL_2_BUTTON_A, CELL_2_BUTTON_B,
CELL_3_0, CELL_3_1, CELL_3_BUTTON_A, CELL_3_BUTTON_B,
CELL_4_0, CELL_4_1, CELL_4_BUTTON_A, CELL_4_BUTTON_B,
CELL_5_0, CELL_5_1, CELL_5_BUTTON_A, CELL_5_BUTTON_B,
CELL_END,

COM_BAUD_0, COM_BAUD_1, COM_BAUD_BUTTON_A, COM_BAUD_BUTTON_B,
COM_PAR_0, COM_PAR_1, COM_PAR_BUTTON_A, COM_PAR_BUTTON_B,
COM_BITS_0, COM_BITS_1, COM_BITS_BUTTON_A, COM_BITS_BUTTON_B,
COM_SWAP_0, COM_SWAP_1, COM_SWAP_BUTTON_A, COM_SWAP_BUTTON_B,
COM_MODE_0, COM_MODE_1, COM_MODE_BUTTON_A, COM_MODE_BUTTON_B,
COM_MOD_ADDR_0, COM_MOD_ADDR_1, COM_MOD_ADDR_BUTTON_A, COM_MOD_ADDR_BUTTON_B,
COM_MOD_ON_0, COM_MOD_ON_1, COM_MOD_ON_BUTTON_A, COM_MOD_ON_BUTTON_B,
COM_END,

TRANS_DEC_S0_0, TRANS_DEC_S0_1, TRANS_DEC_S0_BUTTON_A, TRANS_DEC_S0_BUTTON_B,
TRANS_OFFSET_S0_0, TRANS_OFFSET_S0_1, TRANS_OFFSET_S0_BUTTON_A, TRANS_OFFSET_S0_BUTTON_B,
TRANS_SPAN_S0_0, TRANS_SPAN_S0_1, TRANS_SPAN_S0_BUTTON_A, TRANS_SPAN_S0_BUTTON_B,
TRANS_DEC_S1_0, TRANS_DEC_S1_1, TRANS_DEC_S1_BUTTON_A, TRANS_DEC_S1_BUTTON_B,
TRANS_OFFSET_S1_0, TRANS_OFFSET_S1_1, TRANS_OFFSET_S1_BUTTON_A, TRANS_OFFSET_S1_BUTTON_B,
TRANS_SPAN_S1_0, TRANS_SPAN_S1_1, TRANS_SPAN_S1_BUTTON_A, TRANS_SPAN_S1_BUTTON_B,
TRANS_SPAN_BAT_0, TRANS_SPAN_BAT_1, TRANS_SPAN_BAT_BUTTON_A, TRANS_SPAN_BAT_BUTTON_B,
TRANS_END,
};

#endif /* __UI_H__ */
